import {p,section as s,table,list,note,snippet as q,frame,mistakes,experiments,flow} from './html.mjs';
export const animationChapter = {
  number:23,slug:'a-character-that-walks',part:'V · A room worth walking through',
  title:'A character that walks',
  deck:'A sprite sheet adds poses, not a new rendering system. Keep direction and time in the game, and select an image region through the renderer API.',
  outcome:'The player faces four directions, cycles through walking poses while actually moving, and returns to a directional idle pose when released or blocked.',
  body:s('Animation is a choice of picture',p(`The previous character moved as a still image. We will give that movement a short four-pose cycle and remember which way the player faces. Animation does not require skeletal rigs, a scene graph, another pipeline, or uploading image pixels every frame. We place sixteen poses in one persistent texture and change the UV rectangle of the player’s quad.`)
    + `<figure class="art-preview sprite-sheet-preview"><img src="../project/assets/player-walk.png" width="1254" height="1254" alt="Transparent sprite sheet: four rows facing south, west, east, and north, each with idle and walking poses"><figcaption>Four directions, four poses per direction. Background transparency is stored in the PNG’s alpha channel.</figcaption></figure>`
    + p(`The generated sheet preserves the brown hair, sage jacket, tan trousers, and boots. Its first version accidentally painted a checkerboard background. We rejected that RGB-only output and used a targeted image edit to remove the background, then checked that the replacement was RGBA with transparent empty pixels. This is an asset-validation lesson: a picture that looks transparent in a preview is not proof of alpha. The <a href="../project/assets/ANIMATION-PROMPT.txt">generation prompt</a> and <a href="../project/assets/ANIMATION-ALPHA-PROMPT.txt">transparency correction prompt</a> are saved with the assets.`)
    + p(`The actual sheet is 1254 × 1254, not the requested 1024 × 1024. It has clear separate cells, but the figures are not perfectly registered on a uniform grid. We use reviewed source rectangles and a bottom-center anchor instead of pretending that blindly dividing by four produces a polished animation. The result is a small, stylized walk cycle, not a production animator’s perfectly matched directional gait. Some side-view stepping silhouettes are similar. You can replace the art while retaining the tested animation and rendering contracts.`))
    + s('Add the smallest missing renderer capability',p(`In <code>renderer/renderer.odin</code>, extend Sprite with two optional parameters after tint: <code>uv_min</code> defaults to (0,0), and <code>uv_max</code> defaults to (1,1). Existing room and debug rectangle calls still select the whole image. Replace only the recorded UV calculation, not vertex stride, shaders, bind group layouts, or frame encoding.`)
    + q(23,'renderer/renderer.odin','Sprite :: proc')
    + p(`The four local corners remain (0,0), (1,0), (1,1), (0,1). For each corner, compute <code>uv_min + corner × (uv_max − uv_min)</code>. That maps the same unit quad onto a selected image rectangle. A frame’s position/size still controls geometry; its UV bounds independently control which texels color that geometry. Sprite now checks that the region is positive and within normalized [0,1] bounds. This API serves a real caller need; the renderer still does not know about directions or frame timers.`)
    + table(['Data','Odin vertex bytes','WGSL meaning'],[
      ['World corner','position at offset 0, Float32x2/location 0','Where this corner lands after projection.'],
      ['Selected frame UV corner','uv at offset 8, Float32x2/location 1','Where this corner samples the sheet.'],
      ['Tint','tint at offset 16, Float32x4/location 2','Color/opacity multiplier.'],
      ['Stride','Still 32 bytes','Animation changes values, not the pipeline’s memory contract.'],
    ]))
    + s('Describe the actual asset',p(`Add <code>game/animation.odin</code>. Rows are South, West, East, North in that order. Columns form the idle/passing/step sequence supplied by the artist or generator. Column zero is also the directional idle pose. These are content conventions, not WebGPU enum values.`)
    + q(23,'game/animation.odin','Facing :: enum','Animate :: proc')
    + p(`Each Sprite_Frame stores source-texel minimum corner and extent. The table’s rectangles include two pixels of transparent padding around the main opaque silhouette. <code>tools/inspect-art</code> is a small Odin inspection utility that decodes alpha and prints candidate bounds per cell; it does not alter the PNG, produce a runtime atlas, or draw replacement art. The checked-in table is the actual asset contract and should be reviewed whenever the image changes. Tests ensure all rectangles stay inside SHEET_SIZE.`)
    + p(`A frame’s UV minimum is frame.min / SHEET_SIZE; its maximum is (frame.min + frame.size) / SHEET_SIZE. The maximum describes the far edge, not the final included texel center. Nearest sampling plus transparent gutters avoids neighboring-pose bleed at our scales. If you later add bilinear filtering or mipmaps, atlas gutters and edge extrusion need a deliberate policy; clamp-to-edge clamps the entire texture, not every frame inside it.`)
    + p(`The world size of a cropped frame is source size × PLAYER_TEXEL_SCALE (0.16), retaining a constant texel-to-world scale across poses. We place its bottom center near the feet, one unit below the game anchor, instead of stretching every crop to an identical width and height. Stretching independently would make a wide stepping pose become unnaturally narrow and a taller frame shrink. Cropping/anchoring affects rendering only; the 8 × 4 collision footprint remains unchanged.`))
    + s('Choose a scale that belongs in the room', p(`Compare the player with furniture, not just with the full PNG dimensions. The previous 0.1 scale made a 268-texel-tall crop about 27 world units tall, smaller than the chair’s 38-unit vertical span. At 0.16 the same crop is about 43 units tall, and the other poses range from about 43 to 44 units. This gives the player a more readable presence beside the furniture without changing the room’s 384 × 256 world.`)
    + p(`These are art-direction comparisons, not real-world measurements: the room is drawn in a stylized perspective. Keep a constant scale across poses and inspect both open-floor movement and furniture contact. The bottom-center anchor keeps the boots planted as the sprite grows. The 8 × 4 feet box measures floor contact, so it should not automatically grow with the head and torso. If you deliberately make a wider-bodied character, review the footprint and narrow passages separately.`)
    + p(`The <a href="../appendix/sources.html">verification screenshots</a> show the enlarged final character at native presentation scales. F1 reveals the unchanged feet and obstacle boxes. The body can overlap the chair’s painted pixels at contact because the scene uses a small ground footprint and painter’s order; this simple room does not implement furniture foreground layers or per-object depth sorting.`))
    + s('The game owns direction and time',q(23,'game/animation.odin','Animate :: proc')
    + p(`Animate receives requested direction, actual resolved displacement, and elapsed seconds. Requested direction chooses facing, even when a wall prevents motion: pressing north against the north wall should face north. The dominant requested axis wins; equal diagonal components choose the vertical direction deterministically. Changing direction resets phase so a new row begins consistently. Releasing all keys retains the last facing direction.`)
    + p(`Actual displacement determines whether the player is walking. We use a small squared-distance threshold to suppress floating-point dust at contact. If neither axis moved meaningfully, moving becomes false and phase resets to zero. Thus holding a key against solid furniture produces an idle pose instead of continuously walking in place. Sliding along an edge still produces a walk because a nonzero resolved displacement exists.`)
    + p(`While moving, phase advances in seconds and wraps over four × 0.1 = 0.4 seconds. Current_Frame converts phase to an integer column by division by 0.1. A modulo keeps the clock bounded instead of letting it grow for hours and lose floating-point precision. We do not increment the frame once per render: that would play faster on faster displays. The cycle is time-driven at the chosen fixed movement speed; a future variable-speed character might instead drive phase by distance traveled to reduce foot sliding.`)
    + q(23,'game/animation.odin','Current_Frame :: proc')
    + p(`Current_Frame is a read-only selection. It does not advance phase. If the same simulation state is drawn twice, it chooses the same image both times. Animation phase is presentation state owned by the game because it depends on game meaning—walking, facing, idle—not on a GPU completion callback.`))
    + s('Update after collision; draw after update',q(23,'game/game.odin','Update :: proc')
    + p(`Add Animation to game.State. Save the previous position just before Move and call Animate afterward with the difference. This is why animation sees blocked movement correctly. Using direction × speed × dt as “actual motion” would ignore collision and animate through a wall even though world.position did not change. The original movement solver, dt cap, and keyboard mapping are unchanged.`)
    + q(23,'game/game.odin','Draw :: proc')
    + p(`In game.Init, replace player.png with player-walk.png. We still upload just one player texture once. In Draw, select the current frame, compute its geometry size and anchor, and supply UV bounds through named Sprite arguments. The room and F1 overlay use the default full-image UV rectangle. All player frames share one texture ID, so animation does not add a texture run or a bind-group change.`)
    + note('Retain the earlier asset',`player.png stays in the repository for chapters 19–22. Chapter 23 uses player-walk.png. The final executable does not embed the unused earlier character image. Every checkpoint receives the assets it needs so the previous steps remain independently runnable.`))
    + s('A final animated frame, from input to pixels',flow('Animation selects bytes and UVs; the GPU pipeline stays the same.',['SDL key state','Move / collision','Animate','Frame rectangle','Sprite vertices','GPU sampling'])
    + p(`Startup still follows SDL window → native surface → adapter/device/queue → surface configuration → pipeline/buffers/sampler → game asset upload. During a frame, D supplies an eastward request. Move resolves the displacement. Animate faces east and advances phase only if movement occurred. Current_Frame selects one rectangle from the east row. Sprite writes its UV corners alongside its updated world corners. End_Frame processes callbacks, refreshes configuration if needed, acquires the presentation image, uploads the vertex prefix, encodes room then player then optional overlay, submits, and presents. Temporary surface/encoding references are released; the room and sheet remain resident.`)
    + p(`Surface acquisition precedes vertex upload, so a skipped acquisition avoids that transfer. Animation has changed the values consumed by existing stages, not the ownership of the surface or the meaning of a draw command.`)
    + p(`On contact with the chair, resolved displacement becomes zero. Animate resets to directional column zero. World geometry stops moving, and subsequent frames sample the idle region of the same texture. On release, facing remains east. On a resize, surface dimensions and viewport change, while animation phase, source-texel rectangles, world position, and colliders do not.`))
    + s('Test the clock and the boundary',p(`The final tests add three animation-focused cases: equal elapsed seconds at 60 and 144 updates yield the same phase within tolerance; idle retains facing and resets phase; blocked northward motion chooses a north idle while west/south movement chooses the correct row. Atlas bounds and recorded UV corners are checked as data contracts. These tests complement the native harness, which renders actual sheet frames and checks the final blocked idle state.`)
    + p(`Inspect the real character at a comfortable window scale: no opaque checkerboard, no neighboring poses, no dramatic baseline jumps, and no walking cycle when stopped against furniture. The generated sheet is intentionally modest art. If you refine a frame, review its source rectangle and anchor instead of compensating for an asset problem with collision changes. See the verification appendix for native capture and platform limits.`))
    + frame([['Decode/upload walk sheet','Once in game.Init','All sixteen poses are resident in one GPU texture.'],['Choose facing, update animation phase','Once per simulation update, after collision','Uses requested direction and actual movement.'],['Choose source rectangle and record UVs','Once per player draw','No texture upload or new pipeline is required.'],['Texture binding','Same player run as before','Changing frames within one sheet does not change the texture ID.']])
    + mistakes([['Walk speed depends on FPS','Check whether phase advances in seconds or draw count','Rendering rate does not define elapsed time.'],['Walks in place against a wall','Compare requested movement with resolved displacement','Animation should observe the collision result.'],['Character shifts wildly between frames','Check source rectangles and bottom-center registration','Uniform grid assumptions are unsafe for an imperfectly aligned asset.'],['Shows several characters at once','Inspect UV bounds and normalize by the full sheet size','A frame rectangle is not a new texture; the shader still samples the whole sheet resource.'],['Returns south whenever keys are released','Check facing update condition','Idle should retain direction rather than overwrite it with a default.']])
    + experiments(['Change FRAME_SECONDS from 0.1 to 0.15. Movement speed should stay 72 units/second while the gait slows.','Press diagonally, release, and explain the retained facing using the dominant-axis tie rule.','While F1 is enabled, watch the fixed feet box through a walking cycle. Changing poses must not change collision size.'])
};
